### ISSUE TITLE
Goop install is exiting with status 1

### ISSUE THREAD

**Issue by rbclark** [avishai-ish-shalom/packer-post-processor-docker-dockerfile#1]
I am attempting to build this project on my local machine and am getting the following error:

```
=> Fetching dependencies for code.google.com/p/gosshold...
=> Fetching dependencies for github.com/ActiveState/tail...
=> Fetching dependencies for github.com/going/toolkit...
package code.google.com/p/goprotobuf/proto: unable to detect version control system for code.google.com/ path
github.com/xiocode/toolkit (download)
goop: Command failed with exit status 1
```

Is there any way around this? Is this even a problem? I ran goop go build afterwards and a binary did build without any errors.

**Comment by nukemberg** [comment]
it seems goprotobuf moved to github. try building without the goopfile.lock

**Comment by rbclark** [comment]
Okay thanks that seems to have patched the issue, subsequent calls to goop install with the new Gemfile.lock seem to fail but it at least built successfully, thanks!

**Comment by nukemberg** [comment]
i've opened a pull request for github.com/going/toolkit to fix the import path for the new location of goprotobuf.

**Comment by nukemberg** [comment]
Patch accepted upstream and Goopfile updated to match.

**Comment by rbclark** [comment]
That did it, thanks again and thanks for this extremely useful plugin!
