### ISSUE TITLE
Cannot build the plugin

### ISSUE THREAD

**Issue by pielu** [avishai-ish-shalom/packer-post-processor-docker-dockerfile#3]
Hi,
When running the following I get:

go install github.com/nitrous-io/goop: build output "goop" already exists and is a directory

I followed the instructions in the documentation.

**Comment by nukemberg** [comment]
The readme says to run `go get github.com/nitrous-io/goop && go build github.com/nitrous-io/goop`, not `go install github.com/nitrous-io/goop`

**Comment by pielu** [comment]
That is what I run and what I got in return (the directory exists error). I assume that goop does the "go install" part on user behalf.

**Comment by nukemberg** [comment]
you are running the wrong command. if you already have `goop` installed, build the plugin using the following command: `goop go build`
