### ISSUE TITLE
post-processor fails when using docker 1.8.1

### ISSUE THREAD

**Issue by romankor** [avishai-ish-shalom/packer-post-processor-docker-dockerfile#6]
Gave it a try on 1.7.1 works fine , fails using the same packer.json when using docker 1.8.1.

**Comment by nukemberg** [comment]
logs?

**Comment by romankor** [comment]
when using 1.8.1 
![image](https://cloud.githubusercontent.com/assets/2689706/10050435/fb325398-6224-11e5-92a3-647f01b8dfc0.png)
using 1.7.1
![image](https://cloud.githubusercontent.com/assets/2689706/10050445/0c7b439e-6225-11e5-8b00-44bfe884fd77.png)

I have no logs , even running --debug with packer didnt give me too much info.

**Comment by nukemberg** [comment]
hmm. can you provide your packer template?

**Comment by nukemberg** [comment]
ok, it seems you are hitting docker/docker#16218.
