### ISSUE TITLE
build fails due to broken deeper level dependency

### ISSUE THREAD

**Issue by henning** [avishai-ish-shalom/packer-post-processor-docker-dockerfile#8]
Hi, 
it seems to me that the post processor does not build currently due to some broken dependencies in dependencies:

it's the goop install command that fails, seemingly(I'm not a go expert) at this place:

$ goop install
...
package google.golang.org/grpc
    imports golang.org/x/net/http2
    imports golang.org/x/net/http2/hpack
    imports google.golang.org/grpc/credentials
    imports google.golang.org/api/bigquery/v2
    imports google.golang.org/api/container/v1beta1
    imports google.golang.org/api/container/v1beta1
    imports google.golang.org/api/container/v1beta1: cannot find package "google.golang.org/api/container/v1beta1" in any of:
    /usr/lib/go/src/pkg/google.golang.org/api/container/v1beta1 (from $GOROOT)
    /home/henning/packer-post-processor-docker-dockerfile/.vendor/tmp/src/google.golang.org/api/container/v1beta1 (from $GOPATH)
....
goop: Command failed with exit status 1

[install.txt](https://github.com/avishai-ish-shalom/packer-post-processor-docker-dockerfile/files/38130/install.txt)

**Comment by davidgiesberg** [comment]
This seems similar to #1 - I am not a go expert either, but I just deleted the `Goopfile.lock` and things seem to be working okay now.

**Comment by henning** [comment]
Thanks that made it work!  :)

That being said, I was embarrassed having overseen an obvious solution in another ticket, but I barely see any resemblance in these two issues apart from "updating" but not deleting the goopfile being mentioned ;) 

But maybe updating the checked- in goopfile would be a solution that makes the build run again without modifications from a clean clone.
